environment: <% ENV[ENVIRONMENT, null] %>

sentry:
  sentry_dsn: <% ENV[SENTRY_DSN, null] %>
  version: <% ENV[VERSION, null] %>

logging:
  enabled: <% ENV[LOGGING_ENABLED, true] %>
  level: <% ENV[LOGGING_LEVEL, INFO] %>

s3:
  aws_access_key_id: <% ENV[AWS_ACCESS_KEY_ID] %>
  aws_secret_access_key: <% ENV[AWS_SECRET_ACCESS_KEY] %>
  profile: <% ENV[AWS_PROFILE] %>
  region: us-east-1

backup:
  url: <% ENV[BACKUP_URL] %>
  tables:
    public.ad_facebook:
      query: "select * from public.ad_facebook where advertiser_id = 4"
      location: s3://my-s3-bucket/databudgie/dev/public.ad_facebook.csv

restore:
  url: <% ENV[RESTORE_URL] %>
  tables:
    facebook.ad:
      strategy: use_latest
      location: ${location:public.ad_facebook}
