environment: <% ENV[ENVIRONMENT, null] %>

logging:
  enabled: <% ENV[LOGGING_ENABLED, true] %>
  level: <% ENV[LOGGING_LEVEL, INFO] %>

postgres:
  drivername: postgresql+psycopg2
  host: <% ENV[DATABASE_HOST, null] %>
  username: <% ENV[DATABASE_USERNAME, null] %>
  password: <% ENV[DATABASE_PASSWORD, null] %>
  port: <% ENV[DATABASE_PORT, null] %>
  database: <% ENV[DATABASE_DATABASE, null] %>
