version: 2.1

executors:
  main:
    docker:
      - image: schireson/cicd-python39
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
      - image: postgres:9.6.10-alpine
        environment:
          POSTGRES_DB: dev
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Execute prerequisite setup
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_VERSION=1.1.8 python
            echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> $BASH_ENV
            $HOME/.poetry/bin/poetry config virtualenvs.create false

  aws-create-credentials:
    steps:
      - run:
          name: Create credentials file for AWS
          command: |
            aws configure set default.region "${AWS_DEFAULT_REGION:-us-east-1}"
            printf "${AWS_CREDENTIALS}" > ~/.aws/credentials

  run-make:
    parameters:
      command:
        type: string
    steps:
      - run:
          name: Run a make command
          command: |
            . .venv/bin/activate

            make << parameters.command >>

  setup-python:
    description: Install python dependencies
    steps:
      - setup
      - aws-create-credentials
      - restore_cache:
          key: v2-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            pip install virtualenv
            virtualenv .venv
            . .venv/bin/activate

            make install
      - save_cache:
          paths:
            - .venv
          key: v2-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}

  publish:
    description: Authenticate with a particular ECR instance on AWS
    steps:
      - run:
          command: |
            . .venv/bin/activate

            pip install twine
            lucha aws whitelist --profile artifactory -- lucha cicd publish pypi

jobs:
  lint:
    executor: main
    steps:
      - setup-python
      - run-make:
          command: lint

  test:
    executor: main
    steps:
      - run:
          command: sudo apt-get update && sudo apt-get install postgresql-client
      - setup-python
      - setup_remote_docker
      - run-make:
          command: test

  publish:
    executor: main
    steps:
      - setup-python
      - publish

workflows:
  build_all:
    jobs:
      - lint
      - test
      - publish:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - /^main$/
